-- 001_initial.sql — baseline schema
--
-- Snapshot of every table, column, constraint, and one-time data fix that
-- existed at the moment versioned migrations were introduced.
--
-- This file is intentionally idempotent (CREATE TABLE IF NOT EXISTS,
-- DO/EXCEPTION blocks for ALTERs, WHERE-guarded UPDATEs) so it is safe to
-- apply against:
--   * a fresh database (creates everything from scratch)
--   * the existing prod DB (no-ops; everything already exists)
--   * an ephemeral test DB (no-ops; everything already exists)
--
-- DO NOT EDIT THIS FILE. To add a new schema change, create a new
-- numbered file (e.g. migrations/002_my_change.sql). The migrator runs
-- each file in its own transaction and records the version once it
-- succeeds.

-- Idle-in-transaction safety net: kill anything sitting on a transaction
-- for more than 60 seconds. Wrapped in a DO block so it does not abort the
-- migration when the soularr role does not exist (ephemeral test DBs) or
-- the migrating user lacks ALTER ROLE privilege.
DO $$
BEGIN
    ALTER ROLE soularr SET idle_in_transaction_session_timeout = '60s';
EXCEPTION
    WHEN undefined_object THEN NULL;
    WHEN insufficient_privilege THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS album_requests (
    id SERIAL PRIMARY KEY,

    -- Identity (at least one required)
    mb_release_id TEXT UNIQUE,
    mb_release_group_id TEXT,
    mb_artist_id TEXT,
    discogs_release_id TEXT,

    -- Metadata
    artist_name TEXT NOT NULL,
    album_title TEXT NOT NULL,
    year INTEGER,
    country TEXT,
    format TEXT,

    -- Source
    source TEXT NOT NULL CHECK(source IN ('redownload', 'request', 'manual')),
    source_path TEXT,
    reasoning TEXT,

    -- Status lifecycle
    status TEXT NOT NULL DEFAULT 'wanted'
        CHECK(status IN ('wanted', 'downloading', 'imported', 'manual')),

    -- Retry
    search_attempts INTEGER NOT NULL DEFAULT 0,
    download_attempts INTEGER NOT NULL DEFAULT 0,
    validation_attempts INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ,
    next_retry_after TIMESTAMPTZ,

    -- Import result
    beets_distance REAL,
    beets_scenario TEXT,
    imported_path TEXT,

    -- Quality upgrade
    search_filetype_override TEXT,
    target_format TEXT,
    min_bitrate INTEGER,
    prev_min_bitrate INTEGER,

    -- Legacy Lidarr columns (unused, kept for schema compat)
    lidarr_album_id INTEGER,
    lidarr_artist_id INTEGER,

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS album_tracks (
    id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES album_requests(id) ON DELETE CASCADE,
    disc_number INTEGER NOT NULL DEFAULT 1,
    track_number INTEGER NOT NULL,
    title TEXT NOT NULL,
    length_seconds REAL
);

CREATE TABLE IF NOT EXISTS download_log (
    id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES album_requests(id) ON DELETE CASCADE,
    soulseek_username TEXT,
    filetype TEXT,
    download_path TEXT,
    beets_distance REAL,
    beets_scenario TEXT,
    beets_detail TEXT,
    valid BOOLEAN,
    outcome TEXT CHECK(outcome IN ('success', 'rejected', 'failed', 'timeout', 'force_import')),
    staged_path TEXT,
    error_message TEXT,
    bitrate INTEGER,
    sample_rate INTEGER,
    bit_depth INTEGER,
    is_vbr BOOLEAN,
    was_converted BOOLEAN DEFAULT FALSE,
    original_filetype TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS search_log (
    id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES album_requests(id) ON DELETE CASCADE,
    query TEXT,
    result_count INTEGER,
    elapsed_s REAL,
    outcome TEXT NOT NULL CHECK(outcome IN (
        'found', 'no_match', 'no_results', 'timeout', 'error', 'empty_query'
    )),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS source_denylist (
    id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES album_requests(id) ON DELETE CASCADE,
    username TEXT NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(request_id, username)
);

CREATE TABLE IF NOT EXISTS user_cooldowns (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    cooldown_until TIMESTAMPTZ NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_requests_status ON album_requests(status);
CREATE INDEX IF NOT EXISTS idx_requests_mb_release ON album_requests(mb_release_id);
CREATE INDEX IF NOT EXISTS idx_requests_source ON album_requests(source);
CREATE INDEX IF NOT EXISTS idx_tracks_request ON album_tracks(request_id);
CREATE INDEX IF NOT EXISTS idx_download_log_request ON download_log(request_id);
CREATE INDEX IF NOT EXISTS idx_search_log_request ON search_log(request_id);
CREATE INDEX IF NOT EXISTS idx_denylist_request ON source_denylist(request_id);
CREATE INDEX IF NOT EXISTS idx_cooldown_username ON user_cooldowns(username);

-- ---------------------------------------------------------------------
-- download_log evolutionary columns
-- ---------------------------------------------------------------------

DO $$ BEGIN ALTER TABLE download_log ADD COLUMN bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN sample_rate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN bit_depth INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN is_vbr BOOLEAN; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN was_converted BOOLEAN DEFAULT FALSE; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN original_filetype TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN slskd_filetype TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN slskd_bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN actual_filetype TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN actual_min_bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN spectral_grade TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN spectral_bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN existing_min_bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN existing_spectral_bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN import_result JSONB; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN validation_result JSONB; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE download_log ADD COLUMN final_format TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- ---------------------------------------------------------------------
-- album_requests legacy renames (spectral_* split into last_download / current)
-- ---------------------------------------------------------------------

DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'spectral_bitrate'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'last_download_spectral_bitrate'
    ) THEN
        ALTER TABLE album_requests RENAME COLUMN spectral_bitrate TO last_download_spectral_bitrate;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'spectral_grade'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'last_download_spectral_grade'
    ) THEN
        ALTER TABLE album_requests RENAME COLUMN spectral_grade TO last_download_spectral_grade;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'on_disk_spectral_grade'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'current_spectral_grade'
    ) THEN
        ALTER TABLE album_requests RENAME COLUMN on_disk_spectral_grade TO current_spectral_grade;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'on_disk_spectral_bitrate'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'current_spectral_bitrate'
    ) THEN
        ALTER TABLE album_requests RENAME COLUMN on_disk_spectral_bitrate TO current_spectral_bitrate;
    END IF;
END $$;

-- ---------------------------------------------------------------------
-- album_requests evolutionary columns
-- ---------------------------------------------------------------------

DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN search_filetype_override TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN min_bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN prev_min_bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN verified_lossless BOOLEAN DEFAULT FALSE; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN last_download_spectral_bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN last_download_spectral_grade TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN current_spectral_grade TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN current_spectral_bitrate INTEGER; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN active_download_state JSONB; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE album_requests ADD COLUMN final_format TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- ---------------------------------------------------------------------
-- CHECK constraint upgrades (force_import / manual_import outcomes,
-- 'downloading' status)
-- ---------------------------------------------------------------------

DO $$ BEGIN
    ALTER TABLE download_log DROP CONSTRAINT IF EXISTS download_log_outcome_check;
    ALTER TABLE download_log ADD CONSTRAINT download_log_outcome_check
        CHECK (outcome IN ('success', 'rejected', 'failed', 'timeout', 'force_import', 'manual_import'));
END $$;

DO $$ BEGIN
    ALTER TABLE album_requests DROP CONSTRAINT IF EXISTS album_requests_status_check;
    ALTER TABLE album_requests ADD CONSTRAINT album_requests_status_check
        CHECK(status IN ('wanted', 'downloading', 'imported', 'manual'));
END $$;

-- ---------------------------------------------------------------------
-- Legacy data migrations (one-shot, frozen in this baseline)
-- ---------------------------------------------------------------------

-- Symbolic intent names → concrete CSV values
UPDATE album_requests SET search_filetype_override = 'flac,mp3 v0,mp3 320'
WHERE search_filetype_override IN ('flac_preferred', 'upgrade');

UPDATE album_requests SET search_filetype_override = NULL
WHERE search_filetype_override = 'best_effort';

-- quality_override → search_filetype_override rename
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'quality_override'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'album_requests'
          AND column_name = 'search_filetype_override'
    ) THEN
        ALTER TABLE album_requests RENAME COLUMN quality_override TO search_filetype_override;
    END IF;
END $$;

-- target_format column (added late, but baseline)
DO $$ BEGIN
    ALTER TABLE album_requests ADD COLUMN target_format TEXT;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- Legacy FLAC tier → "lossless" (issue #35)
UPDATE album_requests
   SET search_filetype_override = regexp_replace(
       search_filetype_override,
       '(^|,\s*)flac(\s*,|$)',
       '\1lossless\2',
       'g'
   )
 WHERE search_filetype_override ~ '(^|,\s*)flac(\s*,|$)';

UPDATE album_requests SET target_format = 'lossless'
WHERE target_format = 'flac';

-- Clean up nonsensical multi-value target_format from old upgrade intent
UPDATE album_requests SET target_format = NULL
WHERE target_format LIKE '%,%';
